services:
  backend:
    build:
      context: ./app
    ports:
      - "7088:8000"
    environment: 
      - LDAP_USER=${LDAP_USER}
      - LDAP_PASSWORD=${LDAP_PASSWORD}
      - LDAP_SERVER=${LDAP_SERVER}

